# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b84735e928d56a40a148a304a9948a8368dcdd3d1299df2ded15a14f236fb20b9b7741ac6cec6ad50c5952b468d7137e958e49a774ede03621b6d6f67691946c

test:
  secret_key_base: 43938e035980679e1ad59d49eeb49ea64ce985237b54863b7c2a6282c4452c038860d97571d22ba1c5ba45a9647449ba4fb63cb03bd1671f26da65063d81d5c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
